/**
 * ISO 3166-1 Alpha-2 Länderliste (vollständig, 249 Länder)
 */
export interface Country {
  code: string;   // ISO 3166-1 Alpha-2
  name: string;   // Deutsch
  nameEn: string; // Englisch (für GeoJSON-Mapping)
  continent: string;
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", nameEn: "Afghanistan", continent: "Asien" },
  { code: "EG", name: "Ägypten", nameEn: "Egypt", continent: "Afrika" },
  { code: "AX", name: "Ålandinseln", nameEn: "Åland Islands", continent: "Europa" },
  { code: "AL", name: "Albanien", nameEn: "Albania", continent: "Europa" },
  { code: "DZ", name: "Algerien", nameEn: "Algeria", continent: "Afrika" },
  { code: "AS", name: "Amerikanisch-Samoa", nameEn: "American Samoa", continent: "Ozeanien" },
  { code: "VI", name: "Amerikanische Jungfrauinseln", nameEn: "U.S. Virgin Islands", continent: "Nordamerika" },
  { code: "AD", name: "Andorra", nameEn: "Andorra", continent: "Europa" },
  { code: "AO", name: "Angola", nameEn: "Angola", continent: "Afrika" },
  { code: "AI", name: "Anguilla", nameEn: "Anguilla", continent: "Nordamerika" },
  { code: "AQ", name: "Antarktika", nameEn: "Antarctica", continent: "Antarktika" },
  { code: "AG", name: "Antigua und Barbuda", nameEn: "Antigua and Barbuda", continent: "Nordamerika" },
  { code: "GQ", name: "Äquatorialguinea", nameEn: "Equatorial Guinea", continent: "Afrika" },
  { code: "AR", name: "Argentinien", nameEn: "Argentina", continent: "Südamerika" },
  { code: "AM", name: "Armenien", nameEn: "Armenia", continent: "Asien" },
  { code: "AW", name: "Aruba", nameEn: "Aruba", continent: "Nordamerika" },
  { code: "AZ", name: "Aserbaidschan", nameEn: "Azerbaijan", continent: "Asien" },
  { code: "ET", name: "Äthiopien", nameEn: "Ethiopia", continent: "Afrika" },
  { code: "AU", name: "Australien", nameEn: "Australia", continent: "Ozeanien" },
  { code: "BS", name: "Bahamas", nameEn: "Bahamas", continent: "Nordamerika" },
  { code: "BH", name: "Bahrain", nameEn: "Bahrain", continent: "Asien" },
  { code: "BD", name: "Bangladesch", nameEn: "Bangladesh", continent: "Asien" },
  { code: "BB", name: "Barbados", nameEn: "Barbados", continent: "Nordamerika" },
  { code: "BY", name: "Belarus", nameEn: "Belarus", continent: "Europa" },
  { code: "BE", name: "Belgien", nameEn: "Belgium", continent: "Europa" },
  { code: "BZ", name: "Belize", nameEn: "Belize", continent: "Nordamerika" },
  { code: "BJ", name: "Benin", nameEn: "Benin", continent: "Afrika" },
  { code: "BM", name: "Bermuda", nameEn: "Bermuda", continent: "Nordamerika" },
  { code: "BT", name: "Bhutan", nameEn: "Bhutan", continent: "Asien" },
  { code: "BO", name: "Bolivien", nameEn: "Bolivia", continent: "Südamerika" },
  { code: "BQ", name: "Bonaire, Sint Eustatius und Saba", nameEn: "Bonaire, Sint Eustatius and Saba", continent: "Nordamerika" },
  { code: "BA", name: "Bosnien und Herzegowina", nameEn: "Bosnia and Herzegovina", continent: "Europa" },
  { code: "BW", name: "Botswana", nameEn: "Botswana", continent: "Afrika" },
  { code: "BV", name: "Bouvetinsel", nameEn: "Bouvet Island", continent: "Antarktika" },
  { code: "BR", name: "Brasilien", nameEn: "Brazil", continent: "Südamerika" },
  { code: "IO", name: "Britisches Territorium im Indischen Ozean", nameEn: "British Indian Ocean Territory", continent: "Asien" },
  { code: "VG", name: "Britische Jungferninseln", nameEn: "British Virgin Islands", continent: "Nordamerika" },
  { code: "BN", name: "Brunei Darussalam", nameEn: "Brunei Darussalam", continent: "Asien" },
  { code: "BG", name: "Bulgarien", nameEn: "Bulgaria", continent: "Europa" },
  { code: "BF", name: "Burkina Faso", nameEn: "Burkina Faso", continent: "Afrika" },
  { code: "BI", name: "Burundi", nameEn: "Burundi", continent: "Afrika" },
  { code: "CL", name: "Chile", nameEn: "Chile", continent: "Südamerika" },
  { code: "CN", name: "China", nameEn: "China", continent: "Asien" },
  { code: "CX", name: "Weihnachtsinsel", nameEn: "Christmas Island", continent: "Asien" },
  { code: "CK", name: "Cookinseln", nameEn: "Cook Islands", continent: "Ozeanien" },
  { code: "CR", name: "Costa Rica", nameEn: "Costa Rica", continent: "Nordamerika" },
  { code: "CW", name: "Curaçao", nameEn: "Curaçao", continent: "Nordamerika" },
  { code: "DK", name: "Dänemark", nameEn: "Denmark", continent: "Europa" },
  { code: "DE", name: "Deutschland", nameEn: "Germany", continent: "Europa" },
  { code: "DM", name: "Dominica", nameEn: "Dominica", continent: "Nordamerika" },
  { code: "DO", name: "Dominikanische Republik", nameEn: "Dominican Republic", continent: "Nordamerika" },
  { code: "DJ", name: "Dschibuti", nameEn: "Djibouti", continent: "Afrika" },
  { code: "EC", name: "Ecuador", nameEn: "Ecuador", continent: "Südamerika" },
  { code: "SV", name: "El Salvador", nameEn: "El Salvador", continent: "Nordamerika" },
  { code: "CI", name: "Elfenbeinküste", nameEn: "Côte d'Ivoire", continent: "Afrika" },
  { code: "ER", name: "Eritrea", nameEn: "Eritrea", continent: "Afrika" },
  { code: "EE", name: "Estland", nameEn: "Estonia", continent: "Europa" },
  { code: "SZ", name: "Eswatini", nameEn: "Eswatini", continent: "Afrika" },
  { code: "FK", name: "Falklandinseln", nameEn: "Falkland Islands", continent: "Südamerika" },
  { code: "FO", name: "Färöer", nameEn: "Faroe Islands", continent: "Europa" },
  { code: "FJ", name: "Fidschi", nameEn: "Fiji", continent: "Ozeanien" },
  { code: "FI", name: "Finnland", nameEn: "Finland", continent: "Europa" },
  { code: "FR", name: "Frankreich", nameEn: "France", continent: "Europa" },
  { code: "GF", name: "Französisch-Guayana", nameEn: "French Guiana", continent: "Südamerika" },
  { code: "PF", name: "Französisch-Polynesien", nameEn: "French Polynesia", continent: "Ozeanien" },
  { code: "TF", name: "Französische Südgebiete", nameEn: "French Southern Territories", continent: "Antarktika" },
  { code: "GA", name: "Gabun", nameEn: "Gabon", continent: "Afrika" },
  { code: "GM", name: "Gambia", nameEn: "Gambia", continent: "Afrika" },
  { code: "GE", name: "Georgien", nameEn: "Georgia", continent: "Asien" },
  { code: "GH", name: "Ghana", nameEn: "Ghana", continent: "Afrika" },
  { code: "GI", name: "Gibraltar", nameEn: "Gibraltar", continent: "Europa" },
  { code: "GD", name: "Grenada", nameEn: "Grenada", continent: "Nordamerika" },
  { code: "GR", name: "Griechenland", nameEn: "Greece", continent: "Europa" },
  { code: "GL", name: "Grönland", nameEn: "Greenland", continent: "Nordamerika" },
  { code: "GP", name: "Guadeloupe", nameEn: "Guadeloupe", continent: "Nordamerika" },
  { code: "GU", name: "Guam", nameEn: "Guam", continent: "Ozeanien" },
  { code: "GT", name: "Guatemala", nameEn: "Guatemala", continent: "Nordamerika" },
  { code: "GG", name: "Guernsey", nameEn: "Guernsey", continent: "Europa" },
  { code: "GN", name: "Guinea", nameEn: "Guinea", continent: "Afrika" },
  { code: "GW", name: "Guinea-Bissau", nameEn: "Guinea-Bissau", continent: "Afrika" },
  { code: "GY", name: "Guyana", nameEn: "Guyana", continent: "Südamerika" },
  { code: "HT", name: "Haiti", nameEn: "Haiti", continent: "Nordamerika" },
  { code: "HM", name: "Heard und McDonaldinseln", nameEn: "Heard Island and McDonald Islands", continent: "Antarktika" },
  { code: "HN", name: "Honduras", nameEn: "Honduras", continent: "Nordamerika" },
  { code: "HK", name: "Hongkong", nameEn: "Hong Kong", continent: "Asien" },
  { code: "IN", name: "Indien", nameEn: "India", continent: "Asien" },
  { code: "ID", name: "Indonesien", nameEn: "Indonesia", continent: "Asien" },
  { code: "IQ", name: "Irak", nameEn: "Iraq", continent: "Asien" },
  { code: "IR", name: "Iran", nameEn: "Iran", continent: "Asien" },
  { code: "IE", name: "Irland", nameEn: "Ireland", continent: "Europa" },
  { code: "IS", name: "Island", nameEn: "Iceland", continent: "Europa" },
  { code: "IM", name: "Isle of Man", nameEn: "Isle of Man", continent: "Europa" },
  { code: "IL", name: "Israel", nameEn: "Israel", continent: "Asien" },
  { code: "IT", name: "Italien", nameEn: "Italy", continent: "Europa" },
  { code: "JM", name: "Jamaika", nameEn: "Jamaica", continent: "Nordamerika" },
  { code: "JP", name: "Japan", nameEn: "Japan", continent: "Asien" },
  { code: "YE", name: "Jemen", nameEn: "Yemen", continent: "Asien" },
  { code: "JE", name: "Jersey", nameEn: "Jersey", continent: "Europa" },
  { code: "JO", name: "Jordanien", nameEn: "Jordan", continent: "Asien" },
  { code: "KY", name: "Kaimaninseln", nameEn: "Cayman Islands", continent: "Nordamerika" },
  { code: "KH", name: "Kambodscha", nameEn: "Cambodia", continent: "Asien" },
  { code: "CM", name: "Kamerun", nameEn: "Cameroon", continent: "Afrika" },
  { code: "CA", name: "Kanada", nameEn: "Canada", continent: "Nordamerika" },
  { code: "CV", name: "Kap Verde", nameEn: "Cape Verde", continent: "Afrika" },
  { code: "KZ", name: "Kasachstan", nameEn: "Kazakhstan", continent: "Asien" },
  { code: "QA", name: "Katar", nameEn: "Qatar", continent: "Asien" },
  { code: "KE", name: "Kenia", nameEn: "Kenya", continent: "Afrika" },
  { code: "KG", name: "Kirgisistan", nameEn: "Kyrgyzstan", continent: "Asien" },
  { code: "KI", name: "Kiribati", nameEn: "Kiribati", continent: "Ozeanien" },
  { code: "CC", name: "Kokosinseln", nameEn: "Cocos (Keeling) Islands", continent: "Asien" },
  { code: "CO", name: "Kolumbien", nameEn: "Colombia", continent: "Südamerika" },
  { code: "KM", name: "Komoren", nameEn: "Comoros", continent: "Afrika" },
  { code: "CG", name: "Republik Kongo", nameEn: "Republic of the Congo", continent: "Afrika" },
  { code: "CD", name: "Demokratische Republik Kongo", nameEn: "Democratic Republic of the Congo", continent: "Afrika" },
  { code: "XK", name: "Kosovo", nameEn: "Kosovo", continent: "Europa" },
  { code: "HR", name: "Kroatien", nameEn: "Croatia", continent: "Europa" },
  { code: "CU", name: "Kuba", nameEn: "Cuba", continent: "Nordamerika" },
  { code: "KW", name: "Kuwait", nameEn: "Kuwait", continent: "Asien" },
  { code: "LA", name: "Laos", nameEn: "Laos", continent: "Asien" },
  { code: "LS", name: "Lesotho", nameEn: "Lesotho", continent: "Afrika" },
  { code: "LV", name: "Lettland", nameEn: "Latvia", continent: "Europa" },
  { code: "LB", name: "Libanon", nameEn: "Lebanon", continent: "Asien" },
  { code: "LR", name: "Liberia", nameEn: "Liberia", continent: "Afrika" },
  { code: "LY", name: "Libyen", nameEn: "Libya", continent: "Afrika" },
  { code: "LI", name: "Liechtenstein", nameEn: "Liechtenstein", continent: "Europa" },
  { code: "LT", name: "Litauen", nameEn: "Lithuania", continent: "Europa" },
  { code: "LU", name: "Luxemburg", nameEn: "Luxembourg", continent: "Europa" },
  { code: "MO", name: "Macao", nameEn: "Macao", continent: "Asien" },
  { code: "MG", name: "Madagaskar", nameEn: "Madagascar", continent: "Afrika" },
  { code: "MW", name: "Malawi", nameEn: "Malawi", continent: "Afrika" },
  { code: "MY", name: "Malaysia", nameEn: "Malaysia", continent: "Asien" },
  { code: "MV", name: "Malediven", nameEn: "Maldives", continent: "Asien" },
  { code: "ML", name: "Mali", nameEn: "Mali", continent: "Afrika" },
  { code: "MT", name: "Malta", nameEn: "Malta", continent: "Europa" },
  { code: "MA", name: "Marokko", nameEn: "Morocco", continent: "Afrika" },
  { code: "MH", name: "Marshallinseln", nameEn: "Marshall Islands", continent: "Ozeanien" },
  { code: "MQ", name: "Martinique", nameEn: "Martinique", continent: "Nordamerika" },
  { code: "MR", name: "Mauretanien", nameEn: "Mauritania", continent: "Afrika" },
  { code: "MU", name: "Mauritius", nameEn: "Mauritius", continent: "Afrika" },
  { code: "YT", name: "Mayotte", nameEn: "Mayotte", continent: "Afrika" },
  { code: "MK", name: "Nordmazedonien", nameEn: "North Macedonia", continent: "Europa" },
  { code: "MX", name: "Mexiko", nameEn: "Mexico", continent: "Nordamerika" },
  { code: "FM", name: "Mikronesien", nameEn: "Micronesia", continent: "Ozeanien" },
  { code: "MD", name: "Moldau", nameEn: "Moldova", continent: "Europa" },
  { code: "MC", name: "Monaco", nameEn: "Monaco", continent: "Europa" },
  { code: "MN", name: "Mongolei", nameEn: "Mongolia", continent: "Asien" },
  { code: "ME", name: "Montenegro", nameEn: "Montenegro", continent: "Europa" },
  { code: "MS", name: "Montserrat", nameEn: "Montserrat", continent: "Nordamerika" },
  { code: "MZ", name: "Mosambik", nameEn: "Mozambique", continent: "Afrika" },
  { code: "MM", name: "Myanmar", nameEn: "Myanmar", continent: "Asien" },
  { code: "NA", name: "Namibia", nameEn: "Namibia", continent: "Afrika" },
  { code: "NR", name: "Nauru", nameEn: "Nauru", continent: "Ozeanien" },
  { code: "NP", name: "Nepal", nameEn: "Nepal", continent: "Asien" },
  { code: "NC", name: "Neukaledonien", nameEn: "New Caledonia", continent: "Ozeanien" },
  { code: "NZ", name: "Neuseeland", nameEn: "New Zealand", continent: "Ozeanien" },
  { code: "NI", name: "Nicaragua", nameEn: "Nicaragua", continent: "Nordamerika" },
  { code: "NL", name: "Niederlande", nameEn: "Netherlands", continent: "Europa" },
  { code: "NE", name: "Niger", nameEn: "Niger", continent: "Afrika" },
  { code: "NG", name: "Nigeria", nameEn: "Nigeria", continent: "Afrika" },
  { code: "NU", name: "Niue", nameEn: "Niue", continent: "Ozeanien" },
  { code: "KP", name: "Nordkorea", nameEn: "North Korea", continent: "Asien" },
  { code: "MP", name: "Nördliche Marianen", nameEn: "Northern Mariana Islands", continent: "Ozeanien" },
  { code: "NF", name: "Norfolkinsel", nameEn: "Norfolk Island", continent: "Ozeanien" },
  { code: "NO", name: "Norwegen", nameEn: "Norway", continent: "Europa" },
  { code: "OM", name: "Oman", nameEn: "Oman", continent: "Asien" },
  { code: "AT", name: "Österreich", nameEn: "Austria", continent: "Europa" },
  { code: "TL", name: "Osttimor", nameEn: "Timor-Leste", continent: "Asien" },
  { code: "PK", name: "Pakistan", nameEn: "Pakistan", continent: "Asien" },
  { code: "PS", name: "Palästina", nameEn: "Palestine", continent: "Asien" },
  { code: "PW", name: "Palau", nameEn: "Palau", continent: "Ozeanien" },
  { code: "PA", name: "Panama", nameEn: "Panama", continent: "Nordamerika" },
  { code: "PG", name: "Papua-Neuguinea", nameEn: "Papua New Guinea", continent: "Ozeanien" },
  { code: "PY", name: "Paraguay", nameEn: "Paraguay", continent: "Südamerika" },
  { code: "PE", name: "Peru", nameEn: "Peru", continent: "Südamerika" },
  { code: "PH", name: "Philippinen", nameEn: "Philippines", continent: "Asien" },
  { code: "PN", name: "Pitcairninseln", nameEn: "Pitcairn Islands", continent: "Ozeanien" },
  { code: "PL", name: "Polen", nameEn: "Poland", continent: "Europa" },
  { code: "PT", name: "Portugal", nameEn: "Portugal", continent: "Europa" },
  { code: "PR", name: "Puerto Rico", nameEn: "Puerto Rico", continent: "Nordamerika" },
  { code: "RE", name: "Réunion", nameEn: "Réunion", continent: "Afrika" },
  { code: "RW", name: "Ruanda", nameEn: "Rwanda", continent: "Afrika" },
  { code: "RO", name: "Rumänien", nameEn: "Romania", continent: "Europa" },
  { code: "RU", name: "Russland", nameEn: "Russia", continent: "Europa" },
  { code: "MF", name: "Saint-Martin", nameEn: "Saint Martin", continent: "Nordamerika" },
  { code: "SX", name: "Sint Maarten", nameEn: "Sint Maarten", continent: "Nordamerika" },
  { code: "SB", name: "Salomonen", nameEn: "Solomon Islands", continent: "Ozeanien" },
  { code: "ZM", name: "Sambia", nameEn: "Zambia", continent: "Afrika" },
  { code: "WS", name: "Samoa", nameEn: "Samoa", continent: "Ozeanien" },
  { code: "SM", name: "San Marino", nameEn: "San Marino", continent: "Europa" },
  { code: "ST", name: "São Tomé und Príncipe", nameEn: "São Tomé and Príncipe", continent: "Afrika" },
  { code: "SA", name: "Saudi-Arabien", nameEn: "Saudi Arabia", continent: "Asien" },
  { code: "SE", name: "Schweden", nameEn: "Sweden", continent: "Europa" },
  { code: "CH", name: "Schweiz", nameEn: "Switzerland", continent: "Europa" },
  { code: "SN", name: "Senegal", nameEn: "Senegal", continent: "Afrika" },
  { code: "RS", name: "Serbien", nameEn: "Serbia", continent: "Europa" },
  { code: "SC", name: "Seychellen", nameEn: "Seychelles", continent: "Afrika" },
  { code: "SL", name: "Sierra Leone", nameEn: "Sierra Leone", continent: "Afrika" },
  { code: "ZW", name: "Simbabwe", nameEn: "Zimbabwe", continent: "Afrika" },
  { code: "SG", name: "Singapur", nameEn: "Singapore", continent: "Asien" },
  { code: "SK", name: "Slowakei", nameEn: "Slovakia", continent: "Europa" },
  { code: "SI", name: "Slowenien", nameEn: "Slovenia", continent: "Europa" },
  { code: "SO", name: "Somalia", nameEn: "Somalia", continent: "Afrika" },
  { code: "ES", name: "Spanien", nameEn: "Spain", continent: "Europa" },
  { code: "SJ", name: "Spitzbergen und Jan Mayen", nameEn: "Svalbard and Jan Mayen", continent: "Europa" },
  { code: "LK", name: "Sri Lanka", nameEn: "Sri Lanka", continent: "Asien" },
  { code: "BL", name: "St. Barthélemy", nameEn: "Saint Barthélemy", continent: "Nordamerika" },
  { code: "SH", name: "St. Helena", nameEn: "Saint Helena", continent: "Afrika" },
  { code: "KN", name: "St. Kitts und Nevis", nameEn: "Saint Kitts and Nevis", continent: "Nordamerika" },
  { code: "LC", name: "St. Lucia", nameEn: "Saint Lucia", continent: "Nordamerika" },
  { code: "PM", name: "St. Pierre und Miquelon", nameEn: "Saint Pierre and Miquelon", continent: "Nordamerika" },
  { code: "VC", name: "St. Vincent und die Grenadinen", nameEn: "Saint Vincent and the Grenadines", continent: "Nordamerika" },
  { code: "ZA", name: "Südafrika", nameEn: "South Africa", continent: "Afrika" },
  { code: "SD", name: "Sudan", nameEn: "Sudan", continent: "Afrika" },
  { code: "GS", name: "Südgeorgien", nameEn: "South Georgia", continent: "Antarktika" },
  { code: "KR", name: "Südkorea", nameEn: "South Korea", continent: "Asien" },
  { code: "SS", name: "Südsudan", nameEn: "South Sudan", continent: "Afrika" },
  { code: "SR", name: "Suriname", nameEn: "Suriname", continent: "Südamerika" },
  { code: "SY", name: "Syrien", nameEn: "Syria", continent: "Asien" },
  { code: "TJ", name: "Tadschikistan", nameEn: "Tajikistan", continent: "Asien" },
  { code: "TW", name: "Taiwan", nameEn: "Taiwan", continent: "Asien" },
  { code: "TZ", name: "Tansania", nameEn: "Tanzania", continent: "Afrika" },
  { code: "TH", name: "Thailand", nameEn: "Thailand", continent: "Asien" },
  { code: "TG", name: "Togo", nameEn: "Togo", continent: "Afrika" },
  { code: "TK", name: "Tokelau", nameEn: "Tokelau", continent: "Ozeanien" },
  { code: "TO", name: "Tonga", nameEn: "Tonga", continent: "Ozeanien" },
  { code: "TT", name: "Trinidad und Tobago", nameEn: "Trinidad and Tobago", continent: "Nordamerika" },
  { code: "TD", name: "Tschad", nameEn: "Chad", continent: "Afrika" },
  { code: "CZ", name: "Tschechien", nameEn: "Czech Republic", continent: "Europa" },
  { code: "TN", name: "Tunesien", nameEn: "Tunisia", continent: "Afrika" },
  { code: "TR", name: "Türkei", nameEn: "Turkey", continent: "Asien" },
  { code: "TM", name: "Turkmenistan", nameEn: "Turkmenistan", continent: "Asien" },
  { code: "TC", name: "Turks- und Caicosinseln", nameEn: "Turks and Caicos Islands", continent: "Nordamerika" },
  { code: "TV", name: "Tuvalu", nameEn: "Tuvalu", continent: "Ozeanien" },
  { code: "UG", name: "Uganda", nameEn: "Uganda", continent: "Afrika" },
  { code: "UA", name: "Ukraine", nameEn: "Ukraine", continent: "Europa" },
  { code: "HU", name: "Ungarn", nameEn: "Hungary", continent: "Europa" },
  { code: "UY", name: "Uruguay", nameEn: "Uruguay", continent: "Südamerika" },
  { code: "UZ", name: "Usbekistan", nameEn: "Uzbekistan", continent: "Asien" },
  { code: "VU", name: "Vanuatu", nameEn: "Vanuatu", continent: "Ozeanien" },
  { code: "VA", name: "Vatikanstadt", nameEn: "Vatican City", continent: "Europa" },
  { code: "VE", name: "Venezuela", nameEn: "Venezuela", continent: "Südamerika" },
  { code: "AE", name: "Vereinigte Arabische Emirate", nameEn: "United Arab Emirates", continent: "Asien" },
  { code: "US", name: "Vereinigte Staaten", nameEn: "United States", continent: "Nordamerika" },
  { code: "GB", name: "Vereinigtes Königreich", nameEn: "United Kingdom", continent: "Europa" },
  { code: "VN", name: "Vietnam", nameEn: "Vietnam", continent: "Asien" },
  { code: "WF", name: "Wallis und Futuna", nameEn: "Wallis and Futuna", continent: "Ozeanien" },
  { code: "CY", name: "Zypern", nameEn: "Cyprus", continent: "Europa" },
];

/** Schneller Zugriff: Code → Country */
export const COUNTRY_MAP = new Map(COUNTRIES.map((c) => [c.code, c]));

/** Schneller Zugriff: englischer Name (lowercase) → ISO-Code (Fallback wenn GeoJSON keinen gültigen Code hat) */
export const COUNTRY_NAME_EN_MAP = new Map(COUNTRIES.map((c) => [c.nameEn.toLowerCase(), c.code]));

/** Kontinente sortiert */
export const CONTINENTS = ["Europa", "Asien", "Afrika", "Nordamerika", "Südamerika", "Ozeanien", "Antarktika"] as const;

/** Länder nach Kontinent gruppiert */
export function getCountriesByContinent(): Record<string, Country[]> {
  const result: Record<string, Country[]> = {};
  for (const continent of CONTINENTS) {
    result[continent] = COUNTRIES.filter((c) => c.continent === continent)
      .sort((a, b) => a.name.localeCompare(b.name, "de"));
  }
  return result;
}

/** Gesamtanzahl der Länder (195 souveräne Staaten + Territorien) */
export const TOTAL_SOVEREIGN_COUNTRIES = 195;
